/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug 18 2014, 17:12:05                              *
*        (c) 2014 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "MENU.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0     (GUI_ID_USER + 0x00)
#define ID_TEXT_0     (GUI_ID_USER + 0x01)
#define ID_EDIT_0     (GUI_ID_USER + 0x03)
#define ID_EDIT_1     (GUI_ID_USER + 0x04)
#define ID_TEXT_1     (GUI_ID_USER + 0x05)
#define ID_TEXT_2     (GUI_ID_USER + 0x06)
#define ID_EDIT_2     (GUI_ID_USER + 0x07)
#define ID_EDIT_3     (GUI_ID_USER + 0x08)
#define ID_TEXT_3     (GUI_ID_USER + 0x09)
#define ID_TEXT_4     (GUI_ID_USER + 0x0A)
#define ID_EDIT_4     (GUI_ID_USER + 0x0C)
#define ID_TEXT_5     (GUI_ID_USER + 0x0F)
#define ID_BUTTON_0     (GUI_ID_USER + 0x12)
#define ID_MENU_0     (GUI_ID_USER + 0x13)
#define ID_TEXT_6     (GUI_ID_USER + 0x14)
#define ID_TEXT_7     (GUI_ID_USER + 0x15)
#define ID_TEXT_8     (GUI_ID_USER + 0x16)
#define ID_TEXT_9     (GUI_ID_USER + 0x17)
#define ID_BUTTON_1   (GUI_ID_USER + 0x18)

// USER START (Optionally insert additional defines)
// USER END
int  MAN_SetNotiF(void);
/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "CAN Diag", ID_FRAMEWIN_0, 0, 1, 480, 320, 0, 0x0 },
  { TEXT_CreateIndirect, "ECU Number:", ID_TEXT_0, 204, 160, 87, 31, 0, 0x0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 298, 170, 80, 20, 0, 0x64 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_1, 108, 167, 80, 20, 0, 0x64},
  { TEXT_CreateIndirect, "SW Ver:", ID_TEXT_1, 19, 169, 80, 20, 0, 0x0 },
  { TEXT_CreateIndirect, "HW Ver :", ID_TEXT_2, 19, 195, 71, 28, 0, 0x0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_2, 109, 196, 80, 20, 0, 0x64 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_3, 110, 235, 80, 20, 0, 0x64 },
  { TEXT_CreateIndirect, "CheckSum :", ID_TEXT_3, 20, 235, 80, 20, 0, 0x0 },
  { TEXT_CreateIndirect, "CAN:", ID_TEXT_4, 394, 262, 51, 20, 0, 0x0},
  { EDIT_CreateIndirect, "Edit", ID_EDIT_4, 280, 197, 80, 20, 0, 0x64 },
  { TEXT_CreateIndirect, "GA Type:", ID_TEXT_5, 213, 198, 51, 20, 0, 0x0 },
  { BUTTON_CreateIndirect, "ACP063", ID_BUTTON_0, 150, 51, 87, 44, 0, 0x0 },
  { MENU_CreateIndirect, "Menu", ID_MENU_0, 4, 2, 473, 24, 0, 0x0},
  { TEXT_CreateIndirect, "Prj : ACP063", ID_TEXT_6, 21, 45, 80, 20, 0, 0x0 },
  { TEXT_CreateIndirect, "OK :  GREEN", ID_TEXT_7, 20, 69, 84, 29, 0, 0x64 },
  { TEXT_CreateIndirect, "ERROR :R ED", ID_TEXT_8, 21, 101, 82, 28, 0, 0x0 },
  { TEXT_CreateIndirect, "OPEN : YELLOW", ID_TEXT_9, 19, 131, 85, 27, 0, 0x0 },
  { BUTTON_CreateIndirect, "Notification", ID_BUTTON_1, 210, 258, 76, 29, 0, 0x0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

const char* ECUNameData[8] = 
{
	"ACP063",
	"ACP063-A",
	"ACP063-B",
	"ACP063-C",
	"ACP063-D",
	"ACP063-E",
	"ACP063-F",
	"ACP063-G",
};

const char* NotifButton[2] = 
{
	"OFF",
	"ON",
};

   int      bFlash;
/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  MENU_ITEM_DATA   ItemData;
  WM_HWIN          hItem;
  int              NCode;
  int              Id;
  int              u32Type;

  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
	  case WM_PAINT:
//      GUI_SetColor(GUI_WHITE);
//	  GUI_SetPenSize(5);
//	  GUI_DrawCircle(380, 100, 40);
//	  GUI_DrawCircle(440, 270, 10);

//		GUI_SetColor(GUI_YELLOW);
//		GUI_FillCircle(280, 100, 38);		
//        
//		GUI_SetColor(GUI_GREEN);
//		GUI_FillCircle(440, 270, 9);

	  
		break;
  case WM_INIT_DIALOG:
    //
    // Initialization of 'ECU Number:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
   // TEXT_SetFont(hItem, GUI_FONT_13_ASCII);
    TEXT_SetTextColor(hItem, 0x00400040);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "C0053");
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, 0x00000000);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetText(hItem, "123");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, 0x00000000);
    //
    // Initialization of 'SW Ver:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
   // TEXT_SetFont(hItem, GUI_FONT_13_1);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetText(hItem, "123");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetText(hItem, "123");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
    EDIT_SetText(hItem, "ACP063");
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, 0x00000000);
    //
    // Initialization of 'Menu'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MENU_0);
    ItemData.Flags    = 0;
    ItemData.hSubmenu = 0;
    ItemData.Id       = 0;
    ItemData.pText    = "Seting";
    MENU_AddItem(hItem, &ItemData);
    ItemData.Flags    = 0;
    ItemData.hSubmenu = 0;
    ItemData.Id       = 0;
    ItemData.pText    = "Edite";
    MENU_AddItem(hItem, &ItemData);
    ItemData.Flags    = 0;
    ItemData.hSubmenu = 0;
    ItemData.Id       = 0;
    ItemData.pText    = "HELP";
    MENU_AddItem(hItem, &ItemData);
    //
    // Initialization of 'OK :  GREEN'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetTextColor(hItem, 0x00000000);
    //
    // Initialization of 'ERROR :R ED'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetTextColor(hItem, 0x00000000);
    //
    // Initialization of 'OPEN : YELLOW'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetTextColor(hItem, 0x00000000);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END


	 WM_CreateTimer(WM_GetClientWindow(pMsg->hWin), 0, 100, 0);

    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_3: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_4: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'ACP063'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
		u32Type = MAN_SetType();
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		BUTTON_SetText(hItem, ECUNameData[u32Type]);
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_MENU_0: // Notifications sent by 'Menu'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	case ID_BUTTON_1: // Notifications sent by 'Notification'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
		u32Type = MAN_SetNotiF();
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetText(hItem, NotifButton[u32Type]);
		  // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  case WM_TIMER:
	  if (bFlash)
	  {
		  bFlash = 0;
	  }
	  else
	  {
		  bFlash = 1;
	  }
	  WM_Paint(WM_GetClientWindow(pMsg->hWin));
	 // WM_SendMessage(WM_GetClientWindow(pMsg->hWin), WM_INIT_DIALOG);
	/// WM_RestartTimer((WM_HMEM)(pMsg->Data.v), 500);
    // WM_CreateTimer(WM_GetClientWindow(pMsg->hWin), 0, 100, 0);
	break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateCAN Diag
*/
WM_HWIN CreateCANDiag(void);
WM_HWIN CreateCANDiag(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
